### ISSUE TITLE
Test container should be based on ubuntu-slim

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#105]
To optimize layers in common with other deis components and presumably reduce the final image size. (Although I assume @arschles had good reasons for going with `ubuntu-debootstrap`, which is deprecated now BTW.)

**Comment by helgi** [comment]
Given the DNS issue in alpine:3.3 we may want to just use ubuntu-thin instead to stick with Ubuntu

**Comment by arschles** [comment]
@mboersma I went with `ubuntu-debootstrap` at the time so we didn't have to compile tests with `CGO_ENABLED=0`. Also, that was when we didn't need the ginkgo server running (because we weren't running tests in parallel). I suspect that we need to stay with an image that has libc, so an ubuntu-based image is a really good idea still.

That brings me to your point, @helgi. Basically, I agree. I'll change the title to point to `ubuntu-thin` for now.

**Comment by krancour** [comment]
It _is_ based on alpine.

https://github.com/deis/workflow-e2e/blob/master/Dockerfile#L1

This has been the case since https://github.com/deis/workflow-e2e/pull/175

**Comment by arschles** [comment]
Oops, thanks @krancour. Clearly I didn't do my homework. As far as I know, we're still suffering from the alpine DNS issues in the wild, so I'm still open to switching to ubuntu-slim. I'll leave that up to you guys.

**Comment by krancour** [comment]
I know there are DNS issues with Alpine.  Do we think those are cropping up in these tests?  Or are we just developing a general aversion to Alpine now because of the known issue (even if it may not be affecting us here)?

**Comment by helgi** [comment]
I get network unreachable problems in e2e a lot - I was told we were on ubuntu so I ignored it and took it as a Google Cloud problem, now I'm starting to lean towards Alpine again

**Comment by arschles** [comment]
@krancour @helgi why not test ubuntu in the wild so we can evaluate it?

**Comment by krancour** [comment]
fwiw, these tests work almost flawlessly for me against micro-kube and in AWS.  I don't think I'd let GKE off the hook as the culprit just yet.  I've also noticed in Jenkins a correlation between number of e2e jobs running and likelihood of failure.  That's a casual observation.

But please don't interpret any of this as opposition to ubuntu-thin.  It's not.

**Comment by arschles** [comment]
Also, tangentially on-topic: `ubuntu-slim` may be a good option for us _in general_ it contains a libc shared object that Go binaries can use. This would mean building without `CGO_ENABLED=0`, which would speed up builds in some cases. Take, for example, the `mc` binary (which can be downloaded from https://minio.io/download/):

```console
ENG000656:httpsrv aaronschlesinger$ curl https://dl.minio.io/client/mc/release/linux-amd64/mc > mc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0  2100k      0  0:00:05  0:00:05 --:--:-- 2093k
ENG000656:httpsrv aaronschlesinger$ chmod +x ./mc
```

It doesn't work in an `alpine:3.3` container because of the missing libc shared symbols:

```console
ENG000656:httpsrv aaronschlesinger$ docker run -v $PWD:/pwd -w /pwd alpine:3.3 ./mc
no such file or directory
Error response from daemon: Cannot start container 8589d0ad034b8e57952f7b22a10e172e39a41d86460b922a058481e388c92d3a: [8] System error: no such file or directory
```

But it does in `gcr.io/google_containers/ubuntu-slim:0.2`:

```console
ENG000656:httpsrv aaronschlesinger$ docker run -v $PWD:/pwd -w /pwd gcr.io/google_containers/ubuntu-slim:0.2 ./mc
mc: Configuration written to ‘/root/.mc/config.json’. Please update your access credentials.
mc: Successfully created ‘/root/.mc/share’.
mc: Initialized share uploads ‘/root/.mc/share/uploads.json’ file.
mc: Initialized share downloads ‘/root/.mc/share/downloads.json’ file.
NAME:
  ./mc - Minio Client for cloud storage and filesystems.

USAGE:
  ./mc [FLAGS] COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]

COMMANDS:
  ls		List files and folders.
  mb		Make a bucket or folder.
  cat		Display contents of a file.
  pipe		Write contents of stdin to one target. When no target is specified, it writes to stdout.
  share		Generate URL for sharing.
  cp		Copy one or more objects to a target.
  mirror	Mirror folders recursively from a single source to single destination.
  diff		Compute differences between two folders.
  rm		Remove file or bucket [WARNING: Use with care].
  access	Set public access permissions.
  session	Manage saved sessions of cp and mirror operations.
  config	Manage configuration file.
  update	Check for a new software update.
  version	Print version.
  
GLOBAL FLAGS:
  --help, -h				Show help.
  --config-folder, -C "/root/.mc"	Path to configuration folder.
  --quiet, -q				Suppress chatty console output.
  --no-color				Disable color theme.
  --json				Enable json formatted output.
  --debug				Enable debugging output.
  
VERSION:
  2016-04-01T00:22:11Z
```

**Comment by jchauncey** [comment]
we would also get security scanning from quay for free with ubuntu-slim which would be nice

**Comment by mboersma** [comment]
Currently workflow-e2e is based off `golang:1.6-alpine`.

**Comment by mboersma** [comment]
See deis/docker-go-dev#60 for a potential fix to this issue.

**Comment by bacongobbler** [comment]
This project is now based off of deis/go-dev which is based off of deis/base which is based off of ubuntu-slim, now ubuntu. Closing!
