### ISSUE TITLE
Subset the tests in makefile targets or doc examples

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#111]
Ginkgo has great support for ["focused" specs](https://onsi.github.io/ginkgo/#focused-specs), which are a convenient way to run a subset of the entire e2e suite. While the suite can and should be sped up, it would also be useful for devs to be aware of how to run only relevant e2e tests and speed up their development cycle.

Perhaps adding some example Makefile targets like `make test-apps`, and/or writing a couple examples for the project README.md?

**Comment by Joshua-Anderson** [comment]
Focused tests have been documented in the README.
