### ISSUE TITLE
Fix ps tests and other pending tests introduced in #123

### ISSUE THREAD

**Issue by sgoings** [deis/workflow-e2e#124]
Due to the fact that we were seeing consistent failures related to curl behavior in ps tests, config tests, and a build test, we marked the tests in #123 as pending. For rc1 let's reenable those tests and make them consistently work reallll nice.

**Comment by vdice** [comment]
This requires the following two changes (at minimum):
https://github.com/deis/controller/pull/557 and
https://github.com/deis/router/pull/153
