### ISSUE TITLE
e2e errors when cli performs action before router ready

### ISSUE THREAD

**Issue by vdice** [deis/workflow-e2e#126]
There are a handful of instances in e2e tests (see [here](https://github.com/deis/workflow-e2e/blob/master/tests/ps_test.go#L153), [here](https://github.com/deis/workflow-e2e/blob/master/tests/ps_test.go#L87) and [here](https://github.com/deis/workflow-e2e/blob/master/tests/config_test.go#L32)) where the user is greeted with a 404 when curling the app after certain actions when they should reasonably expect a 200.  

For an example, see the behavior documented in https://github.com/deis/workflow-e2e/issues/69

**Comment by bacongobbler** [comment]
this sounds like the controller is returning the response too early and the application is not yet ready to handle traffic.

**Comment by arschles** [comment]
could this be because the router hasn't yet picked up the new app name?

**Comment by bacongobbler** [comment]
Yep! That is also quite likely. This issue plagued us in v1 as well. We just ensured that the `curl` commands in the end-to-end tests would keep trying for 10 seconds until we got a response, but that wasn't the greatest solution. The best would be for the router to pick up changes instantaneously via watching the API, but right now we're just polling every interval.

**Comment by vdice** [comment]
This remains an issue but with no fix forecast for the `v2.0-rc1` milestone; moving to `v2.0`

**Comment by Joshua-Anderson** [comment]
Is this still a problem? I haven't seen it yet.

**Comment by jchauncey** [comment]
no we can close this.
