### ISSUE TITLE
When app is scaled to zero, should assert response is 503 (not 502)

### ISSUE THREAD

**Issue by krancour** [deis/workflow-e2e#127]

**Comment by vdice** [comment]
See [ps_test](https://github.com/deis/workflow-e2e/blob/9b8f5996618748f6d91146a25f4dd6089ed0d45d/tests/ps_test.go) and this one in [builds_test](https://github.com/deis/workflow-e2e/blob/master/tests/builds_test.go#L143) for needed changes.

**Comment by vdice** [comment]
Tests that had previously asserted response codes of `502` now assert on the correct `503` (see https://github.com/deis/workflow-e2e/blob/master/tests/ps_test.go)  Therefore, closing.
