### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by vdice** [deis/workflow-e2e#128]
We should revisit and update `README.md`.  Here are some initial ideas:

1. example(s) on how to run tests via docker container (see `make docker-build/docker-push/docker-test-integration`)

2. example of how to run tests via a helm [chart](https://github.com/deis/charts), i.e. launching a `deis-tests` (as it is currently known) pod against a `workflow-dev` cluster, a `workflow-beta1-e2e` pod against a `workflow-beta1` cluster chart, etc.

3. amend [Prerequisites](https://github.com/deis/workflow-e2e#prerequisities) section (for instance, `helm install deis/deis` should be `helm install deis/workflow-dev`)

**Comment by bacongobbler** [comment]
all of this has been done over time. Closing!
