### ISSUE TITLE
Proposal: Create a workflow-e2e test suite specifically for the CLI

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#133]
By moving away from using the CLI to drive the current workflow-e2e suite we need to create a supplemental test suite that uses teh CLI to test happy path scenarios. 

The CLI tests would rarely change (unless the CLI is changing - adding/removing commands) while the SDK driven workflow tests would be subject to more rapid change (verifying controller functionality directly).

**Comment by Joshua-Anderson** [comment]
We're now writing CLI unit tests in the CLI repository to test more code paths and option combinations.
