### ISSUE TITLE
Break up tests into smaller examples

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#136]
There are some tests which contain way too many interactions. This causes the tests to run for longer than they really need to when executing them in parallel. We should break up these example groups into smaller tests.

**Comment by arschles** [comment]
Has this been addressed by #157 ?

**Comment by jchauncey** [comment]
Maybe partly. we can close this for now I guess

**Comment by krancour** [comment]
I did break up a bunch of them-- that's why there are more tests now than when I had started #157.  There's still more that can be done probably, but the cases where that is required are probably less obvious now.
