### ISSUE TITLE
Question: do we need the time.Sleep in BeforeSuite?

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#139]
The comment at https://github.com/deis/workflow-e2e/blob/master/tests/tests_suite_test.go#L130 says `// wait for ssh key to propagate. `, but I don't think we need that anymore since the builder no longer relies on confd to propagate SSH keys. It instead checks key validity from the controller on-demand.

Can we remove that sleep?

**Comment by helgi** [comment]
I say remove the sleep, if it doesn't work without it then I'd consider it a bug
