### ISSUE TITLE
Question: Does the Jenkins job on this repo run the e2e tests?

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#141]
As far as I can tell, the e2e tests don't run on pull requests ([example PR run](https://ci.deis.io/job/workflow-e2e-pr/178/)). Is it possible to get them running here?

**Comment by vdice** [comment]
@arschles hmmm perhaps that job was in a not fully configured state with DSL changes in the past few days.  Latest builds appear to be picking off e2e tests (see [here](https://ci.deis.io/job/workflow-e2e-pr/190))

**Comment by mboersma** [comment]
The PR jobs have been humming along smoothly for a while, and empirical evidence shows that e2e changes are tested, so I'm closing this.
