### ISSUE TITLE
Proposal: run one large k8s cluster & install all test Deis clusters onto it

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#142]
As the title indicates, all Deis clusters under test should be run on the same (large) k8s cluster, but under different namespaces. If we do this, we get the following benefits:

- The beginning of a test no longer needs to "find" a new cluster that's available for use
  - Instead, it simply generates a new namespace and installs the Deis cluster & tests into it
- The end of a test can simply `kubectl delete ns $TEST_NAMESPACE` to clean up after itself

Changes will be necessary in the workflow and workflow-e2e charts to enable this, but I don't believe they are large. The nature of these changes, in my mind, are as follows:

- Change all `namespace:` fields to `{{ .namespace }}`
- Add a template that contains the single field `namespace`

I believe that this change would decrease test run complexity, speed up test runs, and increase determinism of test runs.

**Comment by jchauncey** [comment]
The only thing we will have to figure out is how to delete all the apps the e2e tests create. Right now the e2e tests do absolutely 0 cleanup. So I normally run something like the following - `kg ns | sed 1d | awk '{print $1}' | grep test | xargs kubectl delete ns`

**Comment by arschles** [comment]
I'm not 100% familiar with the test harness, but wouldn't the cleanup simply be `kubectl delete ns $TEST_NAMESPACE`?

Here's my very rough outline of what I'm thinking a test run would look like:

1. `TEST_NAMESPACE=deis-workflow-e2e-$(uuidgen)`
2. `echo "$TEST_NAMESPACE" > "$LOCATION_OF_DEIS_CHART"/tpl/namespace.toml` (approximately). Note that this step indicates a small amount of work to be done in the workflow chart - parameterizing the namespace.
3. `helm generate $CHART_NAME && helm install $CHART_NAME`
4. ... wait for all pods to be `Ready` ...
5. Run test in the same namespace as `$TEST_NAMESPACE` (iirc, this would simply be a `helm generate ... && helm install` command as well)
6. When test is done & reported, `kubectl delete ns $TEST_NAMESPACE`

**Comment by jchauncey** [comment]
no because every deploy app is put into its own namespace by default so that would be an internal change we would have to make. I think it might be a good one but im not sure we can do that.

**Comment by arschles** [comment]
@jchauncey ah, forgot about apps! One idea for parallel tests is that we can run a separate server that holds a global set of app names for that test run:

1. Each parallel test writes its app name into the server
2. The server stores each app name (which in turn is a namespace)
3. When the test is completely finished, the `AfterSuite` tells that server to delete all app namespaces

**Comment by jchauncey** [comment]
hrm thats an interesting approach. another would be to have the test suite store all app names created (which we already know) and then in the after suite we nuke them

**Comment by arschles** [comment]
Since each `It` block runs in a separate process, I was under the impression that we couldn't store all app names in-memory in the main process. If that's not the case, then :+1: to your approach!

**Comment by jchauncey** [comment]
no we should be able to do that because i reference the admin user data in all the tests and its created in the before suite

**Comment by arschles** [comment]
:+1: - then this is even easier than what I said.

**Comment by jchauncey** [comment]
I have no idea what data structure we use to hold this information though. This is getting outside of my golang knowledge. So would definitely entertain a PR that tried to implement this.

**Comment by arschles** [comment]
@jchauncey I'll put one up shortly...

**Comment by arschles** [comment]
@jchauncey sorry for the delay - #146 should take care of deleting app namespaces. Note that I haven't tested it yet, however

**Comment by jchauncey** [comment]
So the plan as it stands right now is to do the following - 

1. Create a pool of kubernetes clusters in GKE
1. Create an application that can manage/provision/reclaim said k8s clusters
1. Before we run an e2e test suite we will claim a cluster. 
1. The application will return the `kubeconfig` as the response for claiming a cluster
1. At the end of the test run another job will reap the cluster that was just used.
