### ISSUE TITLE
[Proposal] Remove mutable/'canary' tag process

### ISSUE THREAD

**Issue by vdice** [deis/workflow-e2e#152]
In https://github.com/deis/charts/issues/204 we discussed the practice of pushing mutable/'canary' tags along with immutable tags after component build.  Although the immutable tags are the ones actually promoted in our current CI process, it was suggested that we should remove the practice of pushing mutable tags.  

Therefore, this issue proposes to remove this process.  The change would be to remove the `docker-mutable-push` Makefile command and use thereof in each relevant Deis Workflow component repo.  For an example of said logic, see [Controller](https://github.com/deis/controller/blob/master/versioning.mk).

**Comment by Joshua-Anderson** [comment]
@vdice What's the status on this? Is it still on the backlog?

**Comment by vdice** [comment]
@Joshua-Anderson we do still use the mutable/`canary` artifacts in the [workflow-dev](https://github.com/deis/charts/blob/master/workflow-dev/tpl/generate_params.toml) chart and as this hasn't been prioritized in any backlog, I'm closing for now until if/when this initiative is pushed for again.
