### ISSUE TITLE
Have tests clean up after themselves

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#162]
Tests should at least delete namespaces of apps that they've created. This issue is a continuation of #146, which was reverted by https://github.com/jchauncey/workflow-e2e/commit/116bf930b7d04d82461f99d2b7294a8525e26ec5

Note that https://github.com/deis/k8s-claimer/issues/39 will clean up test namespaces and the `deis` namespace for leased clusters, so this cleanup logic should be toggle-able by an env var.

**Comment by krancour** [comment]
This was mostly addressed by #157, but it's imperfect.  If tests are interrupted or experience catastrophic failures, all bets are off.

**Comment by arschles** [comment]
@krancour https://github.com/deis/k8s-claimer/issues/39 may also help address, but that still needs integration into tests. See https://github.com/deis/jenkins-jobs/issues/51

**Comment by arschles** [comment]
I'm closing this since deis/k8s-claimer#39 has been completed by https://github.com/deis/k8s-claimer/pull/48
