### ISSUE TITLE
Test suite should build deis CLI from source

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#167]
Currently changes to workflow-cli won't be tested fully in e2e since the [client is downloaded from bintray](https://github.com/deis/workflow-e2e/blob/0b0156d020e3eec1f9bc586818b3286f97dde3e4/Dockerfile#L9).

**Comment by Joshua-Anderson** [comment]
Would it maybe make more sense to download the client binary ***of the commit being tested*** from bintray so that the binary that is being distributed to people is the one being tested?

**Comment by bacongobbler** [comment]
Is there a link to retrieve a specific commit? That would also be handy for `install-v2.sh` because that script only grabs the latest client (which a user may not want when installing 2.0 a few months down the road, for example)

**Comment by Joshua-Anderson** [comment]
> Is there a link on bintray to retrieve a specific commit?

`https://bintray.com/deis/deisci/download_file?file_path=deis-<first 7 char of git sha>-<os>-<arch>` seems to work.

**Comment by mboersma** [comment]
See #217. Still updating the test binary manually by SHA. 😞

**Comment by sgoings** [comment]
What about if we wrote a lil' shell script to check to see if WORKFLOW_CLI_SHA (or something like that) is in the Docker run environment, and if so do what @Joshua-Anderson suggests. If not, download the latest version. Essentially it would be a deis cli shim...

**Comment by arschles** [comment]
note that now we've moved built binaries from bintray to google cloud storage, a sample URL to retrieve the CLI for a specific SHA would be: https://storage.googleapis.com/workflow-cli/08a0e40/deis-08a0e40-linux-amd64

**Comment by Joshua-Anderson** [comment]
I opened PR #233 to fix this.
