### ISSUE TITLE
Question: can we make the e2e image smaller?

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#172]
The current image (tagged `git-7da48d1` at https://quay.io/repository/deisci/workflow-e2e?tag=latest&tab=tags) is 296.2 MB. This issue is to discuss any possible strategies for making it smaller.

**Comment by krancour** [comment]
I believe so.  I have it almost working.

**Comment by krancour** [comment]
And fwiw... the existing image is actually much bigger than 296.2.  That's the _compressed_ size that quay.io is showing you.

**Comment by krancour** [comment]
@arschles the only problem I have run into is `kubectl` doesn't work on Alpine.

Seems you have already done something about this?  https://github.com/arschles/alpine-builds

Are there instructions for use somewhere?

**Comment by krancour** [comment]
Nevermind... the scripts therein were easy enough to read... simple.
