### ISSUE TITLE
finish the apps tests

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#19]
there are a few `XIt`s in there: https://github.com/deis/workflow-e2e/blob/master/tests/apps_test.go

**Comment by bacongobbler** [comment]
a lot of the app tests have been knocked out with #64 but there's still `apps:logs` to implement.

**Comment by helgi** [comment]
Should we move it out of the beta then or close this and open up a new one for post-beta when logger is viable?

**Comment by bacongobbler** [comment]
yes. removing from beta.

**Comment by jchauncey** [comment]
`apps:logs` wont happen until we find another place to run the e2e tests or they release 1.2 on GCE.

**Comment by bacongobbler** [comment]
yep, see sgoings/chart-mate#2 for ongoing work on that front. :) Once we can provision a cluster with daemonset support with chart-mate we can flip that feature on and work from there.

**Comment by jchauncey** [comment]
The logger tests were merged. Is there anything else to do here?

**Comment by vdice** [comment]
@jchauncey no, this ticket can be considered finished.
