### ISSUE TITLE
No tests for random appname creation

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#194]
All the `deis apps:create` tests use the `-a | --appname` flag, but there should be at least one spec that allows Workflow controller to generate a random app name.

**Comment by Joshua-Anderson** [comment]
This is tested in the controller and soon in the CLI. Does this need to be tested in e2e?

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/workflow-e2e#10
