### ISSUE TITLE
No tests for "deis git:remote"

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#205]
This convenience command doesn't appear to be covered in e2e tests.

**Comment by bacongobbler** [comment]
test scenario:

 - create app with --no-remote
 - observe no remote was created
 - `deis git:remote`
 - observe remote was created

**Comment by Joshua-Anderson** [comment]
Git remote is a CLI only, so these should probably be added to the CLI. I already have tests for the git package, so this just needs some minor tests for the CMD portion.
