### ISSUE TITLE
Add test to ensure git pushes can be interrupted and subsequent ones will pass

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#207]
After https://github.com/deis/builder/pull/339, a `git push` operation against builder should be able to get killed, and subsequent ones will then succeed (instead of failing with "another push is in progress")

**Comment by mboersma** [comment]
As described in deis/builder#365, further investigation shows that the current behavior ("another git push is in progress") is consistent with other `git` server endpoints, and that making it interruptible would not interoperate with `git`'s [smart protocol](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols) that is in use.

It's still inconvenient that `git push`es have to be serialized, but there isn't an obvious way to remedy this for now.
