### ISSUE TITLE
e2e tests are failing due to missing `deis` client

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow-e2e#221]
As seen from all the recent jobs (https://ci.deis.io/job/workflow-test-pr/2226/console for example):

> /usr/local/bin/deis: line 1: The: not found

The last known good job was build 2218, so this is a recent development.

**Comment by mboersma** [comment]
I opened a shell into node1 and node2 and confirmed there is no `deis` binary in /usr/local/bin.

How is this binary usually created? It's not in the ansible scripts. Is it e2e-runner?

**Comment by bacongobbler** [comment]
The logs are coming directly from workflow-e2e, so my assumption is that the binary isn't present in `quay.io/deisci/workflow-e2e:canary`. I'm just checking to verify.

**Comment by bacongobbler** [comment]
yep:

```
$ docker run quay.io/deisci/workflow-e2e:canary bash -c '/usr/local/bin/deis'
/usr/local/bin/deis: line 1: The: command not found
```

**Comment by bacongobbler** [comment]
Full output:

```
bash-4.3# cat /usr/local/bin/deis
The requested path was not found.
```

So it's a Dockerfile issue.

**Comment by jchauncey** [comment]
The deis cli is managed in the workflow-e2e docke rimage

**Comment by bacongobbler** [comment]
bintray strikes again: https://github.com/deis/workflow-e2e/blob/9214eeeb1434c0d5e30a656cb1ca86a21f06828e/Dockerfile#L15
