### ISSUE TITLE
Add test for concurrent pushes to the builder

### ISSUE THREAD

**Issue by arschles** [deis/workflow-e2e#224]
Two types of tests should be added:

- Concurrent pushes to different repos (all should succeed)
- Concurrent pushes to the same repo (only 1 should succeed)

**Comment by mboersma** [comment]
Test specs that cover this were added to the e2e tests in deis/workflow#235, but this references builder unit or functional tests as well. So let's leave it open but not consider it done yet.

**Comment by mboersma** [comment]
@arschles, is this closed now after deis/builder#361? There are both flavors of concurrent push tests now in e2e, and at least the second case (same repo) in the builder func tests now.

**Comment by arschles** [comment]
@mboersma https://github.com/deis/builder/pull/361 addresses this issue at a unit-test level. I believe that's enough coverage for this particular test case. I'd like to get at least your thoughts as well, though - and anyone else who you believe should weigh in if you think it's appropriate.

**Comment by mboersma** [comment]
> I believe that's enough coverage for this particular test case.

Agreed. I'll go ahead and close this, but if anyone thinks there are more nuances we should capture here, please reopen this or create a new ticket.
