### ISSUE TITLE
test config:set with multi-line values in container

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow-e2e#23]
deis/deis#4844
deis/workflow#268

We have automated tests [here](https://github.com/deis/workflow-e2e/blob/master/tests/config_test.go#L46-L51), but we also need to ensure that the environment variable inside the container is properly escaped like it's done on Heroku.

**Comment by mboersma** [comment]
I think this is fixed in #78, but we should add another spec that specifically tests `deis config:set` with a private key as mentioned in deis/deis#4844 and verify.

**Comment by mboersma** [comment]
I've tested this with the specific data in deis/deis#4844 and I'm convinced that [this test](https://github.com/deis/workflow-e2e/blob/master/tests/config_test.go#L120) covers the same territory.
