### ISSUE TITLE
[jenkins]: e2e job failure due to deis-router CrashLoopBackOff

### ISSUE THREAD

**Issue by vdice** [deis/workflow-e2e#264]
Documenting the following e2e job failure.  In this case, the tests aren't actually run -- the deis-router pod never comes up as it appears to be stuck in a `CrashLoopBackOff` state.

Here is an example job: https://ci.deis.io/job/workflow-test-pr/3738/console

An excerpt from the console output:
```
10:04:14 Waiting for all pods to be running
10:09:48 
...................................................................................................................................................................................Not all pods started.
10:09:49 NAME                          READY     STATUS             RESTARTS   AGE
10:09:49 deis-builder-ilmrh            1/1       Running            1          6m
10:09:49 deis-controller-cnpy7         1/1       Running            1          6m
10:09:49 deis-database-ntcn5           1/1       Running            0          6m
10:09:49 deis-logger-fluentd-30lcg     1/1       Running            0          6m
10:09:49 deis-logger-fluentd-8tvwi     1/1       Running            0          6m
10:09:49 deis-logger-fluentd-coxtc     1/1       Running            0          6m
10:09:49 deis-logger-fluentd-te6qq     1/1       Running            0          6m
10:09:49 deis-logger-fluentd-vjpp5     1/1       Running            0          6m
10:09:49 deis-logger-jnu11             1/1       Running            2          6m
10:09:49 deis-logger-redis-j4b4e       1/1       Running            0          6m
10:09:49 deis-minio-f91cs              1/1       Running            0          6m
10:09:49 deis-monitor-grafana-tlrct    1/1       Running            0          6m
10:09:49 deis-monitor-influxdb-hpq0r   1/1       Running            0          6m
10:09:49 deis-monitor-telegraf-5zany   1/1       Running            1          6m
10:09:49 deis-monitor-telegraf-eu5kc   1/1       Running            1          6m
10:09:49 deis-monitor-telegraf-hye1h   1/1       Running            1          6m
10:09:49 deis-monitor-telegraf-rtuvm   1/1       Running            1          6m
10:09:49 deis-monitor-telegraf-y0w4y   1/1       Running            1          6m
10:09:49 deis-nsqd-aha9w               1/1       Running            0          6m
10:09:49 deis-registry-d3tpg           1/1       Running            3          6m
10:09:49 deis-router-7jg81             0/1       CrashLoopBackOff   6          6m
10:09:49 deis-workflow-manager-qabcn   1/1       Running            0          6m
10:09:49 registry-proxy-477zx          1/1       Running            0          6m
10:09:49 registry-proxy-dw7c0          1/1       Running            0          6m
10:09:49 registry-proxy-n5v8o          1/1       Running            0          6m
10:09:49 registry-proxy-njjvi          1/1       Running            0          6m
10:09:49 registry-proxy-rxowt          1/1       Running            0          6m
10:09:49 Gather pod logs before we delete lease
```

And the [logs](https://ci.deis.io/job/workflow-test-pr/3738/artifact/3738/logs/deis-router-7jg81.log) from the deis-router pod show:
```
2016/07/20 16:10:04 INFO: Starting nginx...
2016/07/20 16:10:04 INFO: nginx started.
2016/07/20 16:10:05 Error building model; not modifying certs or configuration: endpoints "test-296907690" not found.
```

**Comment by bacongobbler** [comment]
For reference that error comes from [this code in the router](https://github.com/deis/router/blob/431f7ac3fbdfc1a17607b359af9212534b494a2d/router.go#L24-L28), which from my hunch would be from [here](https://github.com/deis/router/blob/431f7ac3fbdfc1a17607b359af9212534b494a2d/model/model.go#L369-L373).

**Comment by vdice** [comment]
This is happening routinely in e2e so hoping we can bump the priority on an investigation/fix in next iteration.

**Comment by bacongobbler** [comment]
Another faliure from https://ci.deis.io/job/workflow-test-pr/3831/artifact/3831/logs/deis-router-0jc0e.log

```
2016/07/21 21:18:16 INFO: Starting nginx...
2016/07/21 21:18:16 INFO: nginx started.
2016/07/21 21:18:16 Error building model; not modifying certs or configuration: endpoints "test-296907690" not found.
```

this does seem intermittent, yet at the same time this happens enough to cause concern. There doesn't seem to be anything painfully obvious [since the last release](https://github.com/deis/router/compare/v2.1.0...master), so maybe it has to be an issue with interacting with the kubernetes API?

**Comment by vdice** [comment]
> ... endpoints "test-296907690" not found.

@bacongobbler Isn't it odd that on a fresh workflow installation, the router is looking for a `test-*` endpoint?  Wouldn't that endpoint come from the later e2e chart install?

**Comment by jchauncey** [comment]
Alright this seemed to be directly related to us not cleaning up the cluster. In fact the e2e-runner was cleaning up the cluster but the namespaces were still in a terminating state (some for as high as 11 days). We have turned on `CLEAN_CLUSTER` for k8s-claimer to see if that helps.

**Comment by jchauncey** [comment]
turning on CLEAN_CLUSTER did not fix the problem really. I ended up having to bounce the 2 clusters affected to get them to remove the terminated namespaces.

**Comment by jchauncey** [comment]
rebooted all clusters. closing this issue for now
