### ISSUE TITLE
Verify that pushing a tag can activate CI jobs

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#267]
The new, individual component-based release process that Workflow is shooting for wants to lean heavily on the mechanism of pushing a GitHub tag. Ideally, just pushing a semver tag would cause all appropriate tests to run, and result in a new production Docker image (or other deliverable).

This was problematic in Jenkins at one point although may be working now. We should revisit this by testing it (perhaps at the next component release opportunity) and know what problems might exist before we leverage it heavily.

**Comment by vdice** [comment]
https://ci.deis.io/job/controller-tag-release/3/console is an example of a successful CI job trigger.  This job was manually generated but set `refspec` to `+refs/tags/*:refs/remotes/origin/tags/*` and `branch` to `*/tags/*` in the `git`/scm block.  (Note that this means multiple jobs are triggered off of the push event, per the wildcards.  We will need logic to check `GIT_BRANCH` and make sure it is the most recent tag -- only then would we proceed.)

**Comment by vdice** [comment]
This has been verified in test jobs generated from in-flight PR https://github.com/deis/jenkins-jobs/pull/168; closing.
