### ISSUE TITLE
(app::deploy): Error while pulling image

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#287]
https://ci.deis.io/job/workflow-test-pr/4685/console

```
Error: Unknown Error (400): {"detail":"(app::deploy): 
Error while pulling image: Get http://localhost:5555/v1/repositories/test-719394541/images: dial tcp 127.0.0.1:5555: connection refused"}
```

cc @kmala

**Comment by jchauncey** [comment]
https://ci.deis.io/job/workflow-test-pr/4690/consoleFull#-105616712157a3886c60b264ffb7461fe6

**Comment by helgi** [comment]
Hasn't been seen in a few months - Lets reopen if it happens again

**Comment by knabben** [comment]
I am using a fresh kube-aws (1.4.4) installation, when I try:

$ deis pull deis/example-go -a casual-occupant

This error comes:
Creating build... Error: Unknown Error (400): {"detail":"Put http://localhost:5555/v1/repositories/casual-occupant/: dial tcp 127.0.0.1:5555: getsockopt: connection refused"}

 The same happens with a local kubeadm.

**Comment by bacongobbler** [comment]
@knabben see https://github.com/deis/registry/issues/64
