### ISSUE TITLE
Cannot talk to leased cluster

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#288]
```
00:00:03.326 Leased cluster lallier for 1600 seconds
00:00:03.326 TOKEN: efbae32a-5b38-11e6-ad5b-02420a240207
00:00:04.097 
Error from server: client: etcd cluster is unavailable or misconfigured
```

https://ci.deis.io/job/workflow-test-pr/4689/console

**Comment by Joshua-Anderson** [comment]
I think this is more an kubernetes issue than anything else. Is there anything we can do other than bounce the cluster or stop reusing clusters?

**Comment by jchauncey** [comment]
Not sure but we dont handle it very well. Its more of an e2e-runner issue but im tracking it here for now

**Comment by helgi** [comment]
https://ci.deis.io/job/workflow-test-pr/4702/console

**Comment by helgi** [comment]
Hasn't been seen in a few months - Lets reopen if it happens again
