### ISSUE TITLE
push/pull already in progress

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-e2e#289]
```
Error: Unknown Error (400): {"detail":"push or pull localhost:5555/test-509786421 is already in progress"}
```

https://ci.deis.io/job/workflow-test-pr/4684/console

**Comment by jchauncey** [comment]
Seen again here - https://ci.deis.io/job/workflow-test-pr/4801/console 

@kmala @arschles thoughts?

**Comment by helgi** [comment]
Hasn't been seen in a few months - Lets reopen if it happens again
