### ISSUE TITLE
Integrate CronJob + garbage collector

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#355]
The e2e chart currently uses a DaemonSet with the spotify-gc container to clean up stale Docker image layers and keep the graph from getting too large. But this is clumsy; it continually fails and `CrashLoop`s with an exponential backoff that becomes stupidly large very quickly.

There must be some way to use the new CronJob construct to run a garbage collector sidecar on each node with a regular schedule.

**Comment by vdice** [comment]
PR issued in https://github.com/kubernetes/charts/pull/982; chart installed on `leeroy`/staging cluster and docs updated with this info.

**Comment by vdice** [comment]
Oops; accidentally closed.  TODOs remaining for this issue are:
 * remove sidecar container from `workflow-e2e` chart
 * ensure `spotify-docker-gc` chart is installed on any leasable e2e clusters

**Comment by vdice** [comment]
This needs to wait until the chart is in stable; see https://github.com/kubernetes/charts/pull/982

**Comment by vdice** [comment]
Work completed in https://github.com/deis/workflow-e2e/pull/362 ; closing.
