### ISSUE TITLE
auth:cancel

### ISSUE THREAD

**Issue by helgi** [deis/workflow-e2e#39]
Test all the auth:cancel scenarios

**Comment by helgi** [comment]
https://github.com/deis/workflow-e2e/blob/a8f115436741a98697e89b552fcb2cafa845ba47/tests/tests_suite_test.go#L131-L132 kinda tests it already but that's an AfterSuite action, so we are hoping an action we want to test already works :) 

Chicken Egg scenario

**Comment by mboersma** [comment]
This is more tested now in e2e, although generally in an `AfterEach` clause, so we still don't explicitly test `auth:cancel` failing, for example.

**Comment by Joshua-Anderson** [comment]
Do we need more auth:cancel tests if it's being tested in the CLI, SDK, and Controller?

Is there any reason for `auth:cancel` to fail other than a user still having apps?
