### ISSUE TITLE
test app needs to be configurable

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#44]
Currently it's hardcoded to Deis' example-go app, but the actual `git` URL used should be customizable  via environment variable or another mechanism, so that any 12-factor app repo (not just those in the deis org) can be run through its paces.

**Comment by Joshua-Anderson** [comment]
Update: We now have buildpack tests that test a variety of buildpacks. I've also updated most of the example apps to have identical output to example-go, so swapping them out should be easier

However, the main tests still use the hardcoded example-go app.

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/workflow-e2e#16
