### ISSUE TITLE
Increase the "slow test" threshold

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-e2e#79]
Ginkgo focuses on unit tests, so its default for when a test is considered abnormally slow is not generous enough for e2e's needs. If possible, this should be bumped up to...two minutes? To avoid spurious warnings like these:
```
• [SLOW TEST:65.671 seconds]
```

**Comment by bacongobbler** [comment]
2 minutes sounds like a fair time to consider a test to be "slow".
